/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package demo.submodule.svc1

class Library {
    val lib: demo.submodule.lib.Library = demo.submodule.lib.Library()

    fun hello(message: String): String {
        return "svc1 -> ${lib.hello(message)}"
    }
}
